name: club_me
description: "The first draft of the ClubMe app."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.142

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

  google_fonts: ^6.2.1
  provider: ^6.1.2
  neon_widgets: ^2.0.0
  go_router: ^13.2.4

  flutter_map: ^6.1.0
  flutter_map_marker_cluster: any
  latlong2: ^0.9.1
  flutter_map_tile_caching: ^9.0.0

  qr_flutter: ^4.1.0

  datepicker_dropdown: ^0.1.0

  fl_chart: ^0.67.0

  gradient_borders: ^1.0.0
  video_player: ^2.8.6
  chewie: ^1.8.1

  permission_handler: ^11.3.1

  firebase_core: ^2.32.0
  firebase_analytics: ^10.10.4

  uuid: ^4.4.0
  supabase_flutter: ^2.3.4

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  get_it: ^7.6.4

  url_launcher: ^6.2.6

  camera: ^0.11.0
  adv_camera: ^3.1.0

  logger: ^2.3.0

  animated_background: ^2.0.0

  timezone: any

  toggle_switch: ^2.3.0

  font_awesome_flutter: ^10.7.0

  flutter_launcher_icons: ^0.13.1

  geolocator: ^12.0.0

  flutter_screenutil: ^5.9.3

  responsive_framework: ^1.4.0

  file_picker: ^8.0.5

  no_screenshot: ^0.0.1+6

  mime: ^1.0.5

  gradient_icon: ^2.0.9

  video_thumbnail: ^0.5.3

  flutter_localizations:
    sdk: flutter
  hive_generator: ^2.0.1

  connectivity_plus: ^6.0.5

  glowy_borders: ^1.0.2

#  workmanager:
#    git:
#      url: https://github.com/absar/flutter_workmanager.git
#      ref: ios-bg-tasks-enh-final

  shared_preferences: ^2.3.2
  google_maps_flutter: ^2.9.0

  # These two for testing purposes. there was a medium article
  # https://gist.github.com/krutikJain/e91c32abb2d2fef3532c77c7e9ce059b
  flutter_polyline_points: ^2.1.0
  location: ^5.0.0

  flutter_faq: ^1.0.1+1

  #  flutter_background_geolocation: ^4.12.0
  # Problem: We need to register the service of the creator but the maven cant find it

  #  flutter_foreground_task: ^8.8.1+1
  # Seems complicated. Not yet tested fully.

  #background_location_tracker: ^1.4.3
  #
  # Don't use it because I get the following errors:
  # Cannot access 'lifecycle': it is private in 'ProxyLifecycleProvider'
  # Cannot weaken access privilege 'public' for 'lifecycle' in 'LifecycleOwner'
  # 'lifecycle' hides member of supertype 'LifecycleOwner' and needs 'override' modifier

  webview_flutter: ^4.9.0

  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

  open_mail_app: ^0.4.5

  image_cropper: ^8.0.2
  crop_image: ^1.0.13
  flutter_image_compress: ^2.3.0

  sign_in_with_apple: ^6.1.3

  flutter_native_splash: ^2.4.1

  widget_to_marker: ^1.0.6

  age_calculator: ^1.0.0

  gal: ^2.3.0

  flutter_svg: ^2.0.15

  purchases_flutter: ^6.0.0

flutter_localizations:
  sdk: flutter

dependency_overrides:
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6


flutter_native_splash:
  color: "#121111"
  image: assets/images/cm_logo_600x600_2.png
  android_12:
    image: assets/images/cm_logo_600x600_2.png
  android: true
  ios: true

# In android/.../res/mipmap-anydpi-v26/ you can adjust the inset so that the icon is not cropped
flutter_launcher_icons:
  image_path: "assets/images/club_me_logo_512x512.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/club_me_logo_512x512.png"
  #adaptive_icon_foreground_inset: 32
  background_color_ios: "#000000"




# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/videos/
    - assets/google_fonts/