// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRp7Q_o8tMe1aO8ea20VmvhHMpLfzH8BA',
    appId: '1:414063517769:web:cb47c459d03d03131f9f98',
    messagingSenderId: '414063517769',
    projectId: 'clubme-ba531',
    authDomain: 'clubme-ba531.firebaseapp.com',
    storageBucket: 'clubme-ba531.appspot.com',
    measurementId: 'G-0GY6P60E77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRXOjjimRCnbIaD9mEVP47ySW6V2rvL4w',
    appId: '1:414063517769:android:8a650d40c95967de1f9f98',
    messagingSenderId: '414063517769',
    projectId: 'clubme-ba531',
    storageBucket: 'clubme-ba531.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPl4W-4FcPmLGUAeig9LIvVKEIFrZEn14',
    appId: '1:414063517769:ios:a2cbdff31c9241531f9f98',
    messagingSenderId: '414063517769',
    projectId: 'clubme-ba531',
    storageBucket: 'clubme-ba531.appspot.com',
    iosBundleId: 'com.szymendera.club-me',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPl4W-4FcPmLGUAeig9LIvVKEIFrZEn14',
    appId: '1:414063517769:ios:74d2d75e39b80ae31f9f98',
    messagingSenderId: '414063517769',
    projectId: 'clubme-ba531',
    storageBucket: 'clubme-ba531.appspot.com',
    iosBundleId: 'com.szymendera.clubme.clubMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRp7Q_o8tMe1aO8ea20VmvhHMpLfzH8BA',
    appId: '1:414063517769:web:267cc561da154dfd1f9f98',
    messagingSenderId: '414063517769',
    projectId: 'clubme-ba531',
    authDomain: 'clubme-ba531.firebaseapp.com',
    storageBucket: 'clubme-ba531.appspot.com',
    measurementId: 'G-78SWLRTDDR',
  );

}